- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop rockstar-container                    #name of container 
    - name: remove container
      shell: docker container rm rockstar-container
    - name: remove docker image
      shell: docker image rm vladkohutych/docker-web                            #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name rockstar-container -p 9000:80 vladkohutych/docker-web     #(docker-job>> name of jenkins job)
